# Generated by Django 4.2.2 on 2024-02-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
