# Generated by Django 4.2.2 on 2024-02-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plan_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='hour',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
