# Generated by Django 4.2.2 on 2024-02-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_plan_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='hour',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True),
        ),
    ]
