# Generated by Django 4.2.2 on 2024-02-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_plan_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='hour',
        ),
        migrations.AddField(
            model_name='plan',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
