# Generated by Django 4.2.2 on 2024-02-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_plan_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='date',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
